### ISSUE TITLE
babel & create-hash

### ISSUE THREAD

**Issue by fanatid** [mappum/bitcoin-protocol#1]
* For what purpose you using `babel` here?
* Why you using `create-hash` instead `crypto.createHash`? `create-hash` is a part of `crypto-browserify`

Thank you!

**Comment by mappum** [comment]
>For what purpose you using babel here?

I set up the npm scripts to build to ES2015 when I do `npm publish`, so that this module can be easily used in browserify bundles (see https://github.com/mappum/bitcoin-protocol/blob/master/package.json#L6-L12).

>Why you using create-hash instead crypto.createHash? create-hash is a part of crypto-browserify

You're right, this isn't necessary, but it does reduce the browserify bundle size since not all of `crpyto` will be included. I'm not very familiar with how `uglify-js` interacts with browserify bundles, so I'm not sure if this is actually worth it. What do you think?

**Comment by fanatid** [comment]
I saw babel in `package.json:scripts`, but don't see any ES6 code except `const`..

<s>`crypto.createHash` two times faster than `create-hash` (tested with sha256 not so long ago)</s> `create-hash` in node.js uses `crypto.createHash`
You right about bundle size, may be even make sense use `sha.js` instead `create-hash` (67kb instead 162kb, 541kb with crypto btw). I think that I shouldn't remove `create-hash` from [bitcoin-merkle-proof](https://github.com/mappum/bitcoin-merkle-proof/pull/2)

**Comment by mappum** [comment]
>I saw babel in package.json:scripts, but don't see any ES6 code except const..

I'm also using the keyless object syntax:
```js
module.exports = {
  createDecodeStream,
  createEncodeStream
}
```
and arrow functions:
```js
exports.fixedString = length => codec(...)
```

**Comment by mappum** [comment]
>I think that I shouldn't remove create-hash from bitcoin-merkle-proof

Oops, I didn't notice you removed it. I'll put it back.

**Comment by fanatid** [comment]
Oh, I see it.. but still don't see sense in this.

**Comment by fanatid** [comment]
@mappum don't you mind if I remove `babel` and rename `createDecodeStream` to `stream.decode` (same with `createEncodeStream`) ?
btw, do you want support webcoin modules only on node >= 4 ?

**Comment by mappum** [comment]
I'd rather not change those names, they make it more Node idiomatic in my
opinion.

Also, let's keep babel to make it easier to browserify. I'd like to support
node < 4 too, but not if it requires a lot of extra work.

**Comment by fanatid** [comment]
Just curious, how babel to make code easier to browserify?

**Comment by mappum** [comment]
By pre-building to ES2015 on npm publish, the package can be used without having to set up babel later. It's hard to babelify dependencies for browserify since it is assumed that packages are already ES2015.

**Comment by fanatid** [comment]
Under removing babel I mean also change code that use ES2016 to ES2015.
