### ISSUE TITLE
varint in datatypes

### ISSUE THREAD

**Issue by fanatid** [mappum/bitcoin-protocol#11]
@mappum can you clarify next moments:
1. Why you use `writeInt32LE` instead `writeUInt32LE` and for what you do `& -1` instead `| 0` or `>>> 0`? https://github.com/mappum/bitcoin-protocol/blob/12e07d237c93af6f5cdadac62c23245be2e80c20/src/dataTypes.js#L82
2. Why your multiply on `0xffffffff` instead `0x0100000000`? https://github.com/mappum/bitcoin-protocol/blob/12e07d237c93af6f5cdadac62c23245be2e80c20/src/dataTypes.js#L107

and btw `| 0` is faster than `Math.floor` :)

**Comment by mappum** [comment]
@fanatid Good catches, you are very observant :+1: Updated to fix these: cf0d9f9c679820ad37da41c8c5abf7cd2cb51571

**Comment by fanatid** [comment]
oops, I was wrong, there only `>>> 0` could be used, because `| 0` gives signed number!
