### ISSUE TITLE
Segregated Witness support

### ISSUE THREAD

**Issue by fanatid** [mappum/bitcoin-protocol#14]
Reference:
- [BIP-0144](https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki)

**Comment by mappum** [comment]
:+1: This will be important

**Comment by fanatid** [comment]
I'll try to do this on this week, so please reserve it for me :)

**Comment by mappum** [comment]
Awesome, let me know if I can do anything to help.

**Comment by mappum** [comment]
BTW, I'll also work on a branch in `bitcoin-net` to integrate segwit.

**Comment by mappum** [comment]
Now segwit transactions are supported in `4.1.0`: https://github.com/mappum/bitcoin-protocol/commit/f2e2b7ee3bb310b1c4bc8c0ed2172f0b6b558bdd
