### ISSUE TITLE
custom available messages

### ISSUE THREAD

**Issue by fanatid** [mappum/bitcoin-protocol#15]
@mappum this package definitely need API for adding custom messages, maybe through `createDecodeStream/createEncodeStream`

it will be helpful for other cryptocurrencies (like dash for example -- https://github.com/UdjinM6/dash/blob/43712ff4deec1c1cd606e70710279ba8bbb986d7/src/darksend.cpp#L48)

/cc @jprichardson

**Comment by jprichardson** [comment]
Would love to see this :+1: - this way `bitcoin-protocol` could be used with other cryptocurrencies.

**Comment by fanatid** [comment]
I thought about this yesterday, probably the best solution here will create package `bitcoin-protocol-messages` and require messages here for stream initialization. Other crypto in its turn can extend `bitcoin-protocol-messages`.

**Comment by mappum** [comment]
I agree, this is important for some currencies. Rather than putting it all in its own package, I think we should just let consumers provide an object with `{ <command>: codec, ... }` which will be added to the built-in messages (and override them if it has a duplicate name).

**Comment by mappum** [comment]
This will work well with Webcoin params (e.g. [webcoin-bitcoin](https://github.com/mappum/webcoin-bitcoin)), so other currencies can just add their codecs in the net params.

**Comment by mappum** [comment]
Custom message codecs can now be used as of 520feb465fd4fb46e6fff70be1084dd9d02c8b80.

This is done via the `messages` property in options to `createEncodeStream` and `createDecodeStream`, which is an object with the format `{ commandName: codec, ... }`. The default messages and types are also now exported as an `extend` function to make it easy to add to or override the standard bitcoin protocol.
