### ISSUE TITLE
Inventory vectors: constants

### ISSUE THREAD

**Issue by fanatid** [mappum/bitcoin-protocol#9]
@mappum please add somewhere constants for inventory vectors: ERROR, MSG_TX, MSG_BLOCK, MSG_FILTERED_BLOCK
https://en.bitcoin.it/wiki/Protocol_documentation#Inventory_Vectors
\+ constants REJECT_*

**Comment by mappum** [comment]
Good idea. Done: 8deb9b5dcf23f4ce372f6c6bb5a1ac0ec490e143

**Comment by fanatid** [comment]
Thank you!
It even can be used in tests: https://github.com/mappum/bitcoin-protocol/blob/53209e8cb6d98f0459cbb0ec0d2ee4992d0e1068/test/integration/regtest.js#L217 :)
